name: NPM Publish
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - uses: JS-DevTools/npm-publish@v4
        with:
          package: ./package.json
